import json
from pathlib import Path

import pytest

from visionpitts import scoring
from visionpitts.config import load_scoring

CFG = load_scoring()
FIDS = [f["id"] for f in CFG["factors"]]
ONES = {f: 1.0 for f in FIDS}


def test_contribution_direction():
    assert scoring.contribution(0.8, 1.0) == pytest.approx(0.8)
    assert scoring.contribution(0.8, -1.0) == pytest.approx(0.2)
    assert scoring.contribution(0.3, -0.5) == pytest.approx(0.35)


def test_scores_are_weighted_average_fits_in_unit_interval():
    x = {"need": 0.9, "market_strength": 0.2, "displacement_risk": 0.8, "subsidy_eligible": 1.0, "transit_access": 0.5, "flood_exposure": 0.1}
    s = scoring.score(x, ONES, CFG)
    assert set(s) == {t["id"] for t in CFG["typologies"]}
    assert all(0.0 <= v <= 1.0 for v in s.values())


def test_all_high_factors_give_score_one_for_positive_only_row():
    """A typology whose fit row is all >= 0 scores exactly 1 when every factor is at its best value."""
    x = {f: 1.0 for f in FIDS}
    x["flood_exposure"] = 0.0  # every row wants low flood
    s = scoring.score(x, ONES, CFG)
    assert s["small_apartment"] == pytest.approx(1.0)
    assert s["senior"] == pytest.approx(1.0)


def test_missing_factor_is_skipped_not_imputed():
    x_full = {"need": 0.5, "market_strength": 0.5, "displacement_risk": 0.5, "subsidy_eligible": 1.0, "transit_access": 0.5, "flood_exposure": 0.5}
    x_missing = {**x_full, "market_strength": None}
    s_missing = scoring.score(x_missing, ONES, CFG)
    w_zero = {**ONES, "market_strength": 0.0}
    s_zero_weight = scoring.score(x_full, w_zero, CFG)
    for k in s_missing:
        assert s_missing[k] == pytest.approx(s_zero_weight[k])


def test_no_data_gives_none():
    s = scoring.score({f: None for f in FIDS}, ONES, CFG)
    assert all(v is None for v in s.values())
    assert scoring.ranking(s) == []


def test_ranking_orders_by_score_and_breaks_ties_in_config_order():
    assert scoring.ranking({"adu": 0.5, "duplex_triplex": 0.9, "townhome": 0.9, "small_apartment": None, "senior": 0.1}) == [
        "duplex_triplex", "townhome", "adu", "senior"]


def test_anti_displacement_weights_raise_displacement_share_of_score():
    x = {"need": 0.9, "market_strength": 0.3, "displacement_risk": 0.9, "subsidy_eligible": 1.0, "transit_access": 0.4, "flood_exposure": 0.3}
    bal = scoring.parts(x, scoring.preset_weights(CFG, "balanced"), CFG, "small_apartment")
    anti = scoring.parts(x, scoring.preset_weights(CFG, "anti_displacement"), CFG, "small_apartment")
    share = lambda ps: next(p["contrib"] for p in ps if p["factor"] == "displacement_risk")  # noqa: E731
    assert share(anti) > share(bal)


def test_stability_is_reproducible_and_bounded():
    x = {"need": 0.9, "market_strength": 0.2, "displacement_risk": 0.8, "subsidy_eligible": 1.0, "transit_access": 0.5, "flood_exposure": 0.1}
    a = scoring.rank_stability(x, ONES, CFG)
    b = scoring.rank_stability(x, ONES, CFG)
    assert a == b
    assert 0.0 <= a["stability"] <= 1.0
    assert a["draws"] == CFG["scoring"]["stability_draws"]


def test_parity_fixture_matches_engine():
    """The fixture is generated by scripts/make_parity_fixture.py and also checked by the TypeScript engine."""
    p = Path(__file__).parent / "fixtures" / "scoring_cases.json"
    if not p.exists():
        pytest.skip("fixture not generated yet")
    cases = json.loads(p.read_text())
    for c in cases:
        s = scoring.score(c["x"], c["weights"], CFG)
        for k, v in c["scores"].items():
            assert (s[k] is None and v is None) or s[k] == pytest.approx(v, abs=1e-9), c["name"]
